### ISSUE TITLE
RemNote Library Report: Bigger LaTeX - different settings for block and in-line LaTeX.

### ISSUE THREAD

**Issue by hugomarins** [hannesfrank/remnote-library#10]
I would like to make a suggestion.

Is there a way of customizing separately "block" latex font-size and regular (in-line) latex?

I think normally we would want bigger fonts for the block latex, in which the formula itself is the center of interest.

But making the fonts too large is bad for in-line latex, making the fonts much larger than the surrounding text, and increasing a lot the line spacing:

![image](https://user-images.githubusercontent.com/54500828/107878624-c5669300-6eb2-11eb-846a-e9cbc24c83c3.png)

Thanks for your wonderful work!

---

- **Id:** com.github.hannesfrank.remnote-library.bigger-latex
- **Version:** 0.1.0
- **Type:** Suggestion

---

**Comment by hannesfrank** [comment]
Thanks for the suggestion! I added an extra setting so you can configure inline and display math separately.

**Comment by hugomarins** [comment]
@hannesfrank Thanks for the upgrade. If I'm not wrong, I think the "tips" (inside /* */) explaining the code (customization) are inverted. The "inline" is for the display; and "blocks" for the inline.

**Comment by hannesfrank** [comment]
Oops, you are right. Fixed! (After build is complete.)
