### ISSUE TITLE
Cant get Super Zen to work

### ISSUE THREAD

**Issue by vgteig** [hannesfrank/remnote-library#11]
Hi, I really like the idea of writing with the super zen ability that this code is supposed to make, but I can't make it work. I try tagging both the document itself and rems with super-zen, super zen and other combinations that I would think would work, but I can't get it to work. Do you have any tip?

**Comment by hannesfrank** [comment]
Can you access this discussion on Discord where a user had the same problem? https://discord.com/channels/689979930804617224/689979930804617283/798785496897290280

(If not I can copy the relevant bits later when I'm on my PC again.)

Another common pitfall is to paste the copied CSS into another code block. You are supposed to paste it into the page directly.

**Comment by hannesfrank** [comment]
Here is how it should look like:
![image](https://user-images.githubusercontent.com/4137110/111431178-bd8d4f00-86fb-11eb-89a4-2f477c622677.png)

It is not enabled by default for only parts of the page.
![image](https://user-images.githubusercontent.com/4137110/111431431-1361f700-86fc-11eb-832f-07aaaeda0856.png)

But you can change the CSS easily yourself if you want that (https://discord.com/channels/689979930804617224/689979930804617283/819636361551282186):

> It has to be on the document/opened page/page title. Click on the bullet before the heading "Super Zen Mode" and it 
> should work. I thought it would make sense this way so you can have a fullscreen writing experience only when zooming in on 
> certain parts of your hierarchy like daily journal and alike.
> Replace data-document-tags with data-rem-container-tags and it should work for your example as well.
