### ISSUE TITLE
Bug & solution: the formula can not be covered completely

### ISSUE THREAD

**Issue by luo-chuan** [hannesfrank/remnote-library#12]
A bug of Active Recall Learning, like this:   
![image](https://user-images.githubusercontent.com/33930736/117155228-2e451380-adef-11eb-85ec-b9b44b8621b2.png)  
solution:  
add this code in css:  

```
color: transparent;
```

after:  
![image](https://user-images.githubusercontent.com/33930736/117156060-e4a8f880-adef-11eb-9f95-268678852adc.png)

**Comment by hannesfrank** [comment]
Thanks for the report and even including a fix!
