### ISSUE TITLE
Display problem for "Codeblock Line Numbers" scroll

### ISSUE THREAD

**Issue by soulertsai** [hannesfrank/remnote-library#14]
When I place my cursor inside the code block or hover on the code block, the line numbers will disappear.
![image](https://user-images.githubusercontent.com/7892194/120256776-760d6c80-c2c1-11eb-9f61-8649649b9148.png)

In other scenario, it works fine and I love it!
![image](https://user-images.githubusercontent.com/7892194/120256852-9e956680-c2c1-11eb-8888-002cdaef9771.png)

Is there any method to make those line numbers display all the time?
Thanks for your efforts on this library!

**Comment by hannesfrank** [comment]
Happy to hear that you like the Library!

I don't know any way to have permanent line numbers.  :( See #6. If you find one,  let me know!

**Comment by soulertsai** [comment]
Got it. Thanks again for quick reply.
I'll close this then.
