### ISSUE TITLE
Could not hide lines in multiline/list/set with "active recall" css

### ISSUE THREAD

**Issue by aQuaYi** [hannesfrank/remnote-library#15]

**Comment by hannesfrank** [comment]
It should work and look like this 😕 

![image](https://user-images.githubusercontent.com/4137110/126879642-06102dae-9411-4bf4-9fa6-315dccd26847.png)

You see the last items of the list starting with `1. first` are hidden.

**Comment by aQuaYi** [comment]
@hannesfrank Could you show your the latest Custom CSS for Hidden multiline/list/set.

I have tried hours, But I never hidden lines.

Thanks in advance.

**Comment by hannesfrank** [comment]
Check if you have the latest version from the library here: https://hannesfrank.github.io/remnote-library/#/scroll/com.github.hannesfrank.remnote-library.active-recall. It should say `version: 0.2.0` as shown in the screenshot. I just tested with a fresh copy from there (which generates the screeshot above when pasting) and it works.

**Comment by aQuaYi** [comment]
Thanks a lot. solved.

**Comment by aQuaYi** [comment]
![2021-07-25_12-30-14](https://user-images.githubusercontent.com/6028869/126887802-310dd8ec-4772-4247-a278-cbf8224b8de7.png)

I know why now.

multiline A lost its RemType. It is none of Concept/Descriptor/Slot/Question.

**Comment by hannesfrank** [comment]
Oh, interesting! Thanks for finding this out!
