### ISSUE TITLE
Code block line numbers disappear when mouse over block

### ISSUE THREAD

**Issue by wrgrant** [hannesfrank/remnote-library#6]
![2020-12-15_12h21_40](https://user-images.githubusercontent.com/3092780/102249268-2cc28f80-3ed0-11eb-895b-b5759ce3dccf.gif)

**Comment by hannesfrank** [comment]
Thank you for the report! :smiley:  

Unfortunately this can not be fixed. RemNote uses a different markup when hovering and focusing a Rem and this markup has no line structure. Sorry.
