### ISSUE TITLE
RemNote Library Report: Column Layout v0.1.0

### ISSUE THREAD

**Issue by n4hm3** [hannesfrank/remnote-library#9]
**Please check first if there is an update of this scroll available.**---- **Id:** com.github.hannesfrank.remnote-library.column-layout- **Version:** 0.1.0- **Type:** Problem/Suggestion (choose one)- [ ] Describe the problem you are having with the scroll or how it should be improved.- [ ] _Add_ a short description to the title (don't replace it completely!) so people know what this is about.- [ ] Make sure to include a screenshot or image to make your issue easy to understand.---
This just doesn't work. I've added the code to custom css and the columns just aren't there.

**Comment by hannesfrank** [comment]
Screenshot please ;) It works fine on my end:

![remnote-library-mini-usage](https://user-images.githubusercontent.com/4137110/107628122-7b866e80-6c60-11eb-9db8-b9da43f13d81.gif)

Just paste and whenever you want to use columns, tag with `#columns`.

**Comment by n4hm3** [comment]
oh, I didn't indent the column. I'm sorry for wasting your time. thank you for the very quick response :)

**Comment by hannesfrank** [comment]
No problem, don't worry! Glad we figured it out! 🤗
